function onto = ontologies()

onto = struct;
onto.miRNA_biogenesis = { ...
	'RNASEN', ...    % DROSHA, pri-miRNA -> pre-miRNA
	'DGCR8', ...     % PASHA, pri-miRNA -> pre-miRNA
	'DICER1', ...    % DICER, pre-miRNA -> mature miRNA
	'XPO5', ...      % Exportin-5, transports pre-miRNA out of the nucleus
	'AGO2', ...      % Argonaute-2, the nuclease component of the RISC
	'TARBP2', ...    % TRBP, facilitates DICER-mediated cleavage of pre-miRNA
	'PRKRA', ...     % PACT, facilitates DICER-mediated cleavage of pre-miRNA
}';

onto.DNA_editing = { ...
	'APOBEC1', ...
	'APOBEC2', ...
	'APOBEC3A', ...
	'APOBEC3B', ...
	'APOBEC3C', ...
	'APOBEC3D', ...
	'APOBEC3E', ...
	'APOBEC3F', ...
	'APOBEC3G', ...
	'APOBEC3H', ...
	'APOBEC4', ...
}';

onto.miRNA_editing = { ...
	'ADAR', ...
	'ADARB1', ...
	'ADARB2', ...
}';

onto.RNA_editing = onto.miRNA_editing;

onto.cancer = { ...
	'TERT', ...      % Telomerase reverse transcriptase
}';

onto.tumor_suppressors = { ...
	'TP53', ...      % Upon DNA damage, activates repair proteins, induces
	                 % growth arrest or initiates apoptosis
	'PTEN', ...      % Prevents cells from dividing too rapidly
	
}';

onto.prostate_cancer_fusion_genes = { ...
	% Genes that participate in the 5' side of fusions.
	'TMPRSS2', 'SLC45A3', 'C15orf21', 'HNRNPA2B1', 'KLK2', 'CANT1', 'DDX5', ...
	'MIPOL1', 'FOXP1', 'ACSL3', 'FKBP5', 'CDKN1A', 'TNPO1', 'ALG5', 'MIER2', ...
	...
	... % Genes that partipate in the 3' side of fusions.
	'ERG', 'ETV1', 'ETV2', 'ETV3', 'ETV4', 'ETV5', 'ELK4', 'CD9', 'IKBKB', 'PIGU', ...
        'RSRC2', ...
}';

onto.breast_cancer = { ...
	'BRMS1', ...
	'SATB1', ...     % Regulates chromatin structure and gene expression,
	                 % Han et al (2008)
}';

onto.uarray_platforms = { ...
	'Affymetrix U95A v2', ...
	'Affymetrix U95B', ...
	'Affymetrix U95C', ...
	'Affymetrix HG U133A', ...
	'Affymetrix HT HG U133A', ...
	'Affymetrix HG U133 Plus 2.0', ...
	'Affymetrix Human Exon 1.0 ST', ...
	'Affymetrix GW SNP 6', ...
	'Affymetrix Human Mapping 250K Sty', ...
	'Affymetrix Human Mapping 250K Nsp', ...
	'Agilent 244K TCGA custom 1', ...
	'Agilent 244K TCGA custom 2', ...
	'Agilent 244K TCGA custom 3', ...
	'Agilent HG CGH 244A', ...
	'Agilent G3 Human CGH 1M', ...
	'Agilent Human miRNA 8x15K', ...
	'Agilent Human miRNA 8x15K v2', ...
}';

onto.sequencing_platforms = { ...
	'Illumina Genome Analyzer', ...
	'Solexa', ...
	'ABI SOLiD 3', ...
	'ABI SOLiD 3+', ...
	'ABI SOLiD 4', ...
	'ABI SOLiD 4hq', ...
	'Helicos Heliscope', ...
}';


